const Report = require('../models/Report');
const { sendMail } = require('../utils/sendMail');

const REPORT_EMAIL = process.env.REPORT_EMAIL || 'skillswaphubb@gmail.com';

const getRangeForPeriod = (period, date) => {
  if (!period || !date) return null;

  const selectedDate = new Date(date);
  if (Number.isNaN(selectedDate.getTime())) return null;
  selectedDate.setHours(0, 0, 0, 0);

  let startDate;
  let endDate;

  switch (period) {
    case 'daily':
      startDate = new Date(selectedDate);
      endDate = new Date(selectedDate);
      endDate.setHours(23, 59, 59, 999);
      break;
    case 'weekly': {
      // Week = Monday..Sunday
      const dayOfWeek = selectedDate.getDay();
      const daysToMonday = dayOfWeek === 0 ? -6 : 1 - dayOfWeek;
      startDate = new Date(selectedDate);
      startDate.setDate(selectedDate.getDate() + daysToMonday);
      startDate.setHours(0, 0, 0, 0);

      endDate = new Date(startDate);
      endDate.setDate(startDate.getDate() + 6);
      endDate.setHours(23, 59, 59, 999);
      break;
    }
    case 'monthly':
      startDate = new Date(selectedDate.getFullYear(), selectedDate.getMonth(), 1);
      endDate = new Date(selectedDate.getFullYear(), selectedDate.getMonth() + 1, 0);
      endDate.setHours(23, 59, 59, 999);
      break;
    default:
      return null;
  }

  return { startDate, endDate };
};

exports.createReport = async (req, res) => {
  try {
    const {
      type,
      email,
      issues = [],
      otherDetails = '',
      video,
      reportedUser,
    } = req.body || {};

    // Prefer authenticated user's email; fall back to body email if provided
    const reporterEmail = (req.user && req.user.email) || email;

    if (!reporterEmail) {
      return res.status(400).json({ message: 'Email is required' });
    }

    if (!type || !['video', 'account'].includes(type)) {
      return res.status(400).json({ message: 'Invalid report type' });
    }

    const doc = new Report({
      type,
      reporter: req.user?._id || undefined,
      reporterEmail,
      issues: Array.isArray(issues) ? issues : [],
      otherDetails,
      videoId: type === 'video' ? (video?._id || video?.id || '') : undefined,
      videoTitle: type === 'video' ? (video?.title || '') : undefined,
      videoOwnerId: type === 'video' ? (video?.userId || '') : undefined,
      reportedUserId:
        type === 'account'
          ? reportedUser?._id || reportedUser?.id || reportedUser?.userId || ''
          : undefined,
      reportedUsername:
        type === 'account' ? (reportedUser?.username || '') : undefined,
      rawContext: { video, reportedUser },
    });

    await doc.save();

    // Send notification email to admin
    try {
      const subject = `New ${type === 'video' ? 'Video' : 'Account'} Report`;
      const html = `
        <div style="font-family: system-ui, Arial; max-width: 640px; margin:0 auto; padding:16px;">
          <h2>New ${type === 'video' ? 'Video' : 'Account'} Report</h2>
          <p><b>From:</b> ${reporterEmail}</p>
          <p><b>Issues:</b> ${(Array.isArray(issues) && issues.length) ? issues.join(', ') : 'Not specified'}</p>
          <p><b>Details:</b> ${otherDetails || '—'}</p>
          ${
            type === 'video'
              ? `<p><b>Video ID:</b> ${doc.videoId || '—'}<br/><b>Title:</b> ${doc.videoTitle || '—'}<br/><b>Owner ID:</b> ${doc.videoOwnerId || '—'}</p>`
              : `<p><b>User ID:</b> ${doc.reportedUserId || '—'}<br/><b>Username:</b> ${doc.reportedUsername || '—'}</p>`
          }
          <p style="margin-top:16px; font-size:12px; color:#64748b;">This message was automatically generated by SkillSwap Hub.</p>
        </div>
      `;
      await sendMail({ to: REPORT_EMAIL, subject, html });
    } catch (e) {
      console.error('[Report] Failed to send report email:', e.message);
    }

    return res.status(201).json({ message: 'Report submitted', report: doc });
  } catch (e) {
    console.error('[Report] Create error:', e);
    return res.status(500).json({ message: 'Server error', details: e.message });
  }
};

exports.listReports = async (req, res) => {
  try {
    const { type, status, period, date, page = 1, limit = 50 } = req.query;
    const filter = {};
    if (type && ['video', 'account'].includes(type)) {
      filter.type = type;
    }
    if (status === 'open') {
      filter.resolved = false;
    } else if (status === 'resolved') {
      filter.resolved = true;
    }

    if (period && period !== 'overall' && date) {
      const range = getRangeForPeriod(period, date);
      if (!range) {
        return res.status(400).json({ message: 'Invalid period/date' });
      }
      filter.createdAt = { $gte: range.startDate, $lte: range.endDate };
    }

    const safeLimit = Math.min(Number(limit) || 50, 100);
    const safePage = Math.max(Number(page) || 1, 1);

    const [reports, count] = await Promise.all([
      Report.find(filter)
        .sort({ createdAt: -1 })
        .limit(safeLimit)
        .skip((safePage - 1) * safeLimit)
        .lean(),
      Report.countDocuments(filter),
    ]);

    return res.status(200).json({
      reports,
      totalPages: Math.ceil(count / safeLimit),
      currentPage: safePage,
      total: count,
    });
  } catch (e) {
    console.error('[Report] List error:', e);
    return res.status(500).json({ message: 'Server error', details: e.message });
  }
};

exports.markResolved = async (req, res) => {
  try {
    const { id } = req.params;
    const report = await Report.findById(id);
    if (!report) {
      return res.status(404).json({ message: 'Report not found' });
    }

    if (!report.resolved) {
      report.resolved = true;
      report.resolvedAt = new Date();
      if (req.user?._id) {
        report.resolvedBy = req.user._id;
      }
      await report.save();
    }

    return res.status(200).json({ message: 'Report resolved', report });
  } catch (e) {
    console.error('[Report] Resolve error:', e);
    return res.status(500).json({ message: 'Server error', details: e.message });
  }
};
