const Report = require('../models/Report');
const { sendMail } = require('../utils/sendMail');

const REPORT_EMAIL = process.env.REPORT_EMAIL || 'skillswaphubb@gmail.com';

exports.createReport = async (req, res) => {
  try {
    const {
      type,
      email,
      issues = [],
      otherDetails = '',
      video,
      reportedUser,
    } = req.body || {};

    // Prefer authenticated user's email; fall back to body email if provided
    const reporterEmail = (req.user && req.user.email) || email;

    if (!reporterEmail) {
      return res.status(400).json({ message: 'Email is required' });
    }

    if (!type || !['video', 'account'].includes(type)) {
      return res.status(400).json({ message: 'Invalid report type' });
    }

    const doc = new Report({
      type,
      reporter: req.user?._id || undefined,
      reporterEmail,
      issues: Array.isArray(issues) ? issues : [],
      otherDetails,
      videoId: type === 'video' ? (video?._id || video?.id || '') : undefined,
      videoTitle: type === 'video' ? (video?.title || '') : undefined,
      videoOwnerId: type === 'video' ? (video?.userId || '') : undefined,
      reportedUserId:
        type === 'account'
          ? reportedUser?._id || reportedUser?.id || reportedUser?.userId || ''
          : undefined,
      reportedUsername:
        type === 'account' ? (reportedUser?.username || '') : undefined,
      rawContext: { video, reportedUser },
    });

    await doc.save();

    // Send notification email to admin
    try {
      const subject = `New ${type === 'video' ? 'Video' : 'Account'} Report`;
      const html = `
        <div style="font-family: system-ui, Arial; max-width: 640px; margin:0 auto; padding:16px;">
          <h2>New ${type === 'video' ? 'Video' : 'Account'} Report</h2>
          <p><b>From:</b> ${reporterEmail}</p>
          <p><b>Issues:</b> ${(Array.isArray(issues) && issues.length) ? issues.join(', ') : 'Not specified'}</p>
          <p><b>Details:</b> ${otherDetails || '—'}</p>
          ${
            type === 'video'
              ? `<p><b>Video ID:</b> ${doc.videoId || '—'}<br/><b>Title:</b> ${doc.videoTitle || '—'}<br/><b>Owner ID:</b> ${doc.videoOwnerId || '—'}</p>`
              : `<p><b>User ID:</b> ${doc.reportedUserId || '—'}<br/><b>Username:</b> ${doc.reportedUsername || '—'}</p>`
          }
          <p style="margin-top:16px; font-size:12px; color:#64748b;">This message was automatically generated by Skill-Swap.</p>
        </div>
      `;
      await sendMail({ to: REPORT_EMAIL, subject, html });
    } catch (e) {
      console.error('[Report] Failed to send report email:', e.message);
    }

    return res.status(201).json({ message: 'Report submitted', report: doc });
  } catch (e) {
    console.error('[Report] Create error:', e);
    return res.status(500).json({ message: 'Server error', details: e.message });
  }
};

exports.listReports = async (req, res) => {
  try {
    const { type, status } = req.query;
    const filter = {};
    if (type && ['video', 'account'].includes(type)) {
      filter.type = type;
    }
    if (status === 'open') {
      filter.resolved = false;
    } else if (status === 'resolved') {
      filter.resolved = true;
    }
    const reports = await Report.find(filter)
      .sort({ createdAt: -1 })
      .lean();
    return res.status(200).json({ reports });
  } catch (e) {
    console.error('[Report] List error:', e);
    return res.status(500).json({ message: 'Server error', details: e.message });
  }
};

exports.markResolved = async (req, res) => {
  try {
    const { id } = req.params;
    const report = await Report.findById(id);
    if (!report) {
      return res.status(404).json({ message: 'Report not found' });
    }

    if (!report.resolved) {
      report.resolved = true;
      report.resolvedAt = new Date();
      if (req.user?._id) {
        report.resolvedBy = req.user._id;
      }
      await report.save();
    }

    return res.status(200).json({ message: 'Report resolved', report });
  } catch (e) {
    console.error('[Report] Resolve error:', e);
    return res.status(500).json({ message: 'Server error', details: e.message });
  }
};
