import React from "react";

const TermsConditions = () => (
  <div className="max-w-3xl mx-auto px-4 py-10 text-gray-800">
    <h1 className="text-3xl font-bold mb-4">SkillSwap Hub – Terms &amp; Conditions</h1>
    <p className="text-sm text-gray-500 mb-6">Last Updated: August 2025</p>
  <p className="mb-4">These Terms &amp; Conditions apply to all Users accessing the SkillSwap Hub platform, website (<a href="https://skillswaphub.in" target="_blank" rel="noopener noreferrer" className="text-blue-600 underline">www.skillswaphub.in</a>), and associated services. By using the platform, users provide implied consent to these Terms. Users are strongly encouraged to read and understand these terms fully before accessing or using the platform. SkillSwap Hub reserves the right to enforce these terms at all times and to update them periodically to reflect the platform’s evolving operations, features, and legal obligations.</p>

    <h2 className="text-xl font-semibold mt-8 mb-2">1. Introduction</h2>
    <p className="mb-4">SkillSwap Hub is a world-first peer-to-peer learning and micro-tutoring platform designed to allow users to seek knowledge, teach skills, and earn rewards simultaneously. The platform aims to create a community where learners and tutors can interact, exchange skills, and benefit mutually through structured micro-sessions, job interview, group discussions, and personalized guidance. These Terms &amp; Conditions form a legally binding agreement between SkillSwap Hub and every user accessing the platform. The platform may also offer premium services, gamified learning, AI-assisted recommendations, and other features that require users to comply with these rules. The introduction section establishes the purpose and scope of the agreement, clarifying that continued use implies acceptance of these Terms. Users are responsible for understanding the platform’s nature, functionality, and applicable policies. SkillSwap Hub strives to provide a safe and productive learning environment while protecting intellectual property, privacy, and overall platform integrity.</p>

    <h2 className="text-xl font-semibold mt-8 mb-2">2. Acceptance of Terms</h2>
    <p className="mb-4">By accessing, registering, or using any feature of SkillSwap Hub, users explicitly acknowledge that they accept all terms, policies, and guidelines outlined in this document. Use of the platform without consent is strictly prohibited. Users who do not agree with any provision must immediately discontinue access. Acceptance covers all existing and future platform features, including live tutoring sessions, group discussions, quizzes, wallet transactions, skillCoin and gamification features. Users also acknowledge that SkillSwap Hub may update these Terms periodically, and continued usage constitutes acceptance of such updates. Any violation of these terms can result in immediate account suspension or termination. Users must also understand that the platform relies on mutual trust and ethical behavior among users, and acceptance of terms includes adherence to conduct, privacy, intellectual property, and other regulatory obligations.</p>

    <h2 className="text-xl font-semibold mt-8 mb-2">3. Eligibility</h2>
    <p className="mb-4">Users must be 13 years or older to access SkillSwap Hub independently. Minors below 18 require explicit parental or guardian consent before creating an account or participating in any platform activities. Certain services or features may be restricted regionally due to local laws or regulatory constraints. By registering, users represent and warrant that they meet these eligibility requirements and have the authority to provide accurate information, including parental consent where necessary. Failure to meet eligibility standards may lead to account suspension or permanent termination. SkillSwap Hub reserves the right to verify age or consent and may request documentation at any time. Users are also responsible for ensuring compliance with regional restrictions and applicable laws, including data privacy regulations. Any false representation of age, consent, or location is a violation of these Terms and may result in immediate account closure. Eligible users can access all free features, participate in gamified activities, and interact with tutors and peers, provided they adhere to the platform’s ethical and legal guidelines.</p>

    <h2 className="text-xl font-semibold mt-8 mb-2">4. User Account Creation &amp; Security</h2>
    <p className="mb-4">Creating an account requires users to provide accurate and up-to-date information, including full name, valid email, phone number, and other requested details. Users are solely responsible for maintaining account confidentiality, including passwords and authentication methods. Unauthorized access due to user negligence or compromised credentials is the user’s responsibility. Multiple accounts without explicit SkillSwap Hub approval are strictly prohibited. Users must notify SkillSwap Hub immediately of any suspected account compromise. Accounts may only be shared with authorized family members or as permitted under platform rules. SkillSwap Hub implements technical security measures to protect account data but is not responsible for losses due to user negligence. Security protocols include password hashing, two-factor authentication (if enabled), and monitoring of suspicious activity. Users must not attempt hacking, phishing, or any unauthorized access to other users’ accounts or platform data. Failure to comply can result in permanent suspension, legal action, or financial liability.</p>

    <h2 className="text-xl font-semibold mt-8 mb-2">5. User Roles &amp; Responsibilities</h2>
    <p className="mb-4">SkillSwap Hub users can operate as Learners, Tutors, or both, depending on their preferences and platform permissions. Learners must actively engage with content, attend sessions responsibly, and provide honest feedback. Tutors are responsible for preparing material, delivering structured sessions, and maintaining ethical conduct. All users must avoid harassment, discrimination, or unethical practices. Misconduct, including hate speech, bullying, or spamming, is strictly prohibited. Users must respect intellectual property and avoid plagiarism. Participation in gamified features, quizzes, and leaderboard activities must comply with fair-play rules. Tutors must ensure content accuracy and disclose any sponsored or promotional material transparently. Users are expected to maintain professionalism and respect for peers, instructors, and platform operations at all times. SkillSwap Hub reserves the right to review user behavior and enforce penalties, including temporary or permanent suspension, for violations. Users are encouraged to report misconduct via the platform’s support channels to ensure a safe and inclusive environment.</p>

    <h2 className="text-xl font-semibold mt-8 mb-2">6. Platform Usage Guidelines</h2>
    <p className="mb-4">SkillSwap Hub provides a variety of features, including live tutoring sessions, group discussions, job interview, and interactive learning modules. Users must adhere to all operational rules for each feature. Participation in group discussions requires courteous communication, avoiding spamming, offensive language, or any disruptive behavior. competitions, and leaderboard-based games must be completed honestly, without cheating or manipulation. Content uploaded or shared must comply with platform policies and must not infringe on intellectual property rights. Users must respect others’ privacy and refrain from sharing personal data without consent. Violations of usage guidelines may result in warnings, account suspension, or termination. SkillSwap Hub continually monitors activity to ensure compliance and maintain a safe and productive learning environment. Users are encouraged to familiarize themselves with detailed usage instructions available on the platform.</p>

    <h2 className="text-xl font-semibold mt-8 mb-2">7. Wallet, Credits &amp; Payment Terms</h2>
    <p className="mb-4">SkillSwap Hub uses the SkillCoin system, which is an exclusive credit-based wallet. These coins never expire, meaning you can use your earned or purchased SkillCoins anytime without worrying about expiry. SkillCoins are available only on the SkillSwap Hub platform—either when you make a purchase or earn them through platform activities such as learning, referrals, contests, or tasks. Any third-party or external source claiming to offer or sell SkillCoins is not authorized, and the platform is not responsible for such offers. Remember, SkillCoins are valid only on the SkillSwap Hub platform and can be used exclusively here.<br />Any payment or purchase made on the platform is considered successful only when the transaction is completed, and SkillSwap Hub provides a success notification, email, or payment ID as confirmation. Users must note that a transaction is valid only after receiving confirmation from the platform. Using SkillCoins, you can purchase sessions, courses, premium features, redeem rewards, and other services.<br />Users are responsible for the safe and responsible use of their SkillCoins. SkillSwap Hub ensures that all payments are transparent and trackable, providing proper records of each transaction. In case of any issue or dispute, users can contact the support team to verify their payment status and SkillCoin balance.</p>

    <h2 className="text-xl font-semibold mt-8 mb-2">8. AI Matchmaking Disclaimer</h2>
    <p className="mb-4">SkillSwap Hub leverages AI-powered matchmaking to recommend tutors, learners, and suitable sessions based on user preferences, skills, learning goals, and interaction history. The AI provides recommendations only and does not guarantee a perfect match. Users are encouraged to evaluate suggested matches critically and provide feedback to improve future recommendations. The platform continuously updates AI algorithms to enhance accuracy, relevance, and efficiency, but SkillSwap Hub is not liable for outcomes of AI suggestions, including missed opportunities or mismatched sessions. Users should exercise discretion in selecting tutors, courses, or peer interactions and are responsible for their learning experience. AI recommendations are generated based on available data, and incomplete or inaccurate user profiles may affect results. SkillSwap Hub may use anonymized data to train AI models, ensuring privacy and confidentiality. Users are encouraged to report any technical errors, bias, or concerns regarding AI matchmaking. Participation in AI-assisted features constitutes acceptance of this disclaimer, acknowledging that AI tools aid decisions but do not replace personal judgment or responsibility.</p>

    <h2 className="text-xl font-semibold mt-8 mb-2">9. Content Rights and Ownership</h2>
    <p className="mb-4">All content uploaded, created, or shared on SkillSwap Hub, including lessons, videos, quizzes, notes, and interactive material, is owned by the respective users or tutors. Tutors retain intellectual property rights for educational material they produce. By uploading content, users grant SkillSwap Hub a non-exclusive, worldwide, royalty-free license to display, promote, distribute, and use such content on the platform and associated marketing channels. Users must ensure that content does not violate copyright, trademark, or any third-party rights. SkillSwap Hub has the right to remove, modify, or restrict content if it is found to be inappropriate, offensive, or in violation of Terms. Users cannot claim ownership of other users’ content or redistribute it without consent. Content may also be used for analytics, AI recommendations, or learning personalization, while maintaining confidentiality. SkillSwap Hub actively protects tutor content and discourages plagiarism. Users uploading infringing content may face legal consequences, account suspension, or permanent termination. By contributing content, users confirm that they own rights or have obtained permission, ensuring compliance with all applicable laws.</p>

    <h2 className="text-xl font-semibold mt-8 mb-2">10. Prohibited Activities</h2>
    <p className="mb-4">Users must refrain from any activities that compromise platform integrity, security, or user experience. Prohibited actions include impersonation, phishing, data scraping, reverse engineering, hacking, or attempting to access restricted content. Illegal activities, harassment, spamming, distribution of malware, or offensive material are strictly forbidden. Users must not misuse platform features to gain unfair advantage or disrupt learning processes. SkillSwap Hub monitors for suspicious behavior and may impose account penalties, temporary suspension, or permanent termination on violators. Users must not interfere with other users’ experience, share confidential data, or engage in fraudulent activities. Prohibited activities also include unauthorized financial transactions, fake reviews, or AI system abuse. SkillSwap Hub reserves the right to report serious violations to law enforcement authorities. Users are responsible for understanding all platform rules, and ignorance of policies will not excuse violations. Compliance ensures a safe, fair, and productive learning environment for all participants.</p>

    <h2 className="text-xl font-semibold mt-8 mb-2">11. Termination &amp; Suspension of Account</h2>
    <p className="mb-4">SkillSwap Hub may suspend or terminate accounts at its discretion due to violations of Terms, inactivity, fraudulent behavior, or repeated misconduct. Users may also voluntarily delete their accounts, with all personal data handled according to the Privacy Policy. Account suspension may be temporary, allowing users to resolve issues or appeal decisions. Permanent termination involves revoking platform access and removing content, including wallet funds or rewards, subject to applicable refund policies. Appeals or review requests are considered case-by-case, and the decision of SkillSwap Hub management is final. Users must settle outstanding obligations, disputes, or pending financial transactions before account deletion. Termination does not relieve users from liabilities incurred during account activity, including unpaid subscriptions or fraudulent usage. Communication regarding account suspension or termination will be sent via email or in-platform notifications. SkillSwap Hub reserves the right to enforce policy updates affecting active or terminated accounts, ensuring compliance with laws and platform integrity.</p>

    <h2 className="text-xl font-semibold mt-8 mb-2">12. Data Privacy &amp; Usage</h2>
    <p className="mb-4">User data collected on SkillSwap Hub is used solely for operational, educational, and platform enhancement purposes. Data includes personal information, session participation, interactions, feedback, wallet transactions, and behavioral analytics. SkillSwap Hub implements industry-standard security measures to protect against unauthorized access, modification, or disclosure. Users consent to data processing, storage, and retention as outlined in the detailed Privacy Policy. Data may be anonymized for AI training, analytics, and improving recommendation algorithms. SkillSwap Hub does not sell personal data to third parties. Users may request access, correction, or deletion of personal data in accordance with applicable laws. Third-party services integrated with the platform, such as payment gateways or video tools, may have separate privacy policies, and SkillSwap Hub is not responsible for their data handling. Users are encouraged to review Privacy Policies of all third-party services they use. Data privacy ensures a secure, transparent, and trustworthy environment for learning, financial transactions, and interactions.</p>

    <h2 className="text-xl font-semibold mt-8 mb-2">13. Third-Party Services</h2>
    <p className="mb-4">SkillSwap Hub integrates third-party services to enhance functionality, including payment gateways, video conferencing tools, analytics, and cloud infrastructure. These services are governed by separate agreements and privacy policies. Users accessing third-party features must comply with their respective terms. SkillSwap Hub is not liable for errors, downtime, data loss, or misconduct resulting from third-party service failures. Payment processing, session delivery, or analytics outcomes may occasionally be affected by third-party actions, and users acknowledge this risk. SkillSwap Hub may recommend or link third-party services for convenience, but endorsement is not implied. Users must use caution and discretion when interacting with third-party tools. SkillSwap Hub ensures vendor reliability and security but cannot control external service operations. Complaints related to third-party services should be addressed both to the service provider and SkillSwap Hub support for coordination. Continuous monitoring ensures third-party integration complements platform safety and performance.</p>

    <h2 className="text-xl font-semibold mt-8 mb-2">14. Intellectual Property Rights (IPR)</h2>
    <p className="mb-4">All SkillSwap Hub intellectual property, including brand name, logo, designs, platform code, and proprietary content, is legally protected. Users may not copy, clone, distribute, or use platform intellectual property without written authorization. Violations of IPR may result in legal action, account termination, or financial penalties. Tutors retain rights to original educational content but grant SkillSwap Hub a non-exclusive license for platform use. Users may not exploit IPR for commercial purposes outside the platform. Respecting intellectual property is essential for sustainable and ethical platform growth. Users must report suspected infringement to support or legal channels. SkillSwap Hub actively enforces IPR protection through monitoring, automated tools, and legal remedies. Users must acknowledge that unauthorized reproduction or use of content is strictly prohibited and punishable under Indian laws.</p>

    <h2 className="text-xl font-semibold mt-8 mb-2">15. Disclaimers and Limitation of Liability</h2>
    <p className="mb-4">SkillSwap Hub operates on an “as-is” basis, providing educational tools, AI recommendations, and interactive features. Technical errors, connectivity issues, or third-party failures may occur, and the platform is not liable for direct or indirect losses arising from usage. Users are responsible for personal decisions, learning outcomes, and financial transactions. SkillSwap Hub does not guarantee uninterrupted service, specific learning results, or error-free operations. Third-party integrations are also outside platform liability, including payment gateways, video providers, and analytics tools. Users agree that engagement is voluntary, and SkillSwap Hub is not responsible for outcomes from tutor advice, AI recommendations, or gamification results. Liability is limited to the maximum extent permitted by law, ensuring platform sustainability and continuous service delivery. Users assume responsibility for complying with local laws, privacy regulations, and ethical conduct while using the platform.</p>

    <h2 className="text-xl font-semibold mt-8 mb-2">16. Refund &amp; Cancellation Policy</h2>
    <p className="mb-4">SkillSwap Hub maintains a transparent and fair Refund &amp; Cancellation Policy to ensure financial security and trust for all users. Since the platform operates on a SkillCoin-based credit system, all purchases, session bookings, and feature redemptions use SkillCoins. Users must review and accept this policy before using any paid services or redeeming SkillCoins.<br />Refunds for SkillCoin transactions are generally not applicable, as SkillCoins are non-refundable once earned, purchased, or redeemed. Exceptions may be considered only in cases of platform errors, undelivered sessions, or technical issues verified by SkillSwap Hub. Users must provide transaction details, evidence of issue, and relevant context to request an exception. Completed 1:1 sessions, group discussions, or job interview practices are not eligible for refunds.<br />SkillSwap Hub ensures that all SkillCoin transactions are transparent, trackable, and confirmed via notification, email, or transaction ID. Users are responsible for verifying details before redeeming SkillCoins. Any disputes regarding SkillCoin usage, accidental deductions, or platform errors are resolved at the sole discretion of SkillSwap Hub management.<br />This policy guarantees clarity, fairness, and accountability, maintaining a safe learning and earning experience while protecting platform integrity and user trust.</p>

    <h2 className="text-xl font-semibold mt-8 mb-2">17. Changes to Terms</h2>
    <p className="mb-4">SkillSwap Hub may update these Terms periodically to reflect legal requirements, platform enhancements, or operational changes. Updates are communicated via email, in-platform notifications, or banners. Continued use after changes indicates acceptance of the updated Terms. Users are responsible for reviewing changes regularly. Major changes, such as subscription policies, refund rules, or privacy adjustments, will receive highlighted notifications. Users may discontinue use if they disagree with modifications. SkillSwap Hub reserves the right to enforce revised terms retroactively where legally permissible. Changes may also impact gamification, AI features, content usage, or financial transactions. By using the platform, users acknowledge that updates are part of maintaining a safe, legal, and user-friendly environment.</p>

    <h2 className="text-xl font-semibold mt-8 mb-2">18. Governing Law &amp; Jurisdiction</h2>
    <p className="mb-4">These Terms are governed by Indian laws, specifically under the jurisdiction of Dehradun, Uttarakhand. All disputes, claims, or legal proceedings arising from platform usage must be resolved within this jurisdiction. Users agree to submit to courts or arbitration in Dehradun for dispute resolution. SkillSwap Hub may enforce its rights through civil or legal proceedings where necessary. Users must comply with local regulations regarding online learning, intellectual property, and financial transactions. Governing law ensures clarity, legal protection, and consistent resolution of disputes. Users outside India acknowledge that Indian law governs their use of the platform and any enforcement actions.</p>

    <h2 className="text-xl font-semibold mt-8 mb-2">19. Contact Information</h2>
    <p className="mb-4">For support, queries, or reporting abuse, users may contact SkillSwap Hub at:<br />• Support Email: skillswaphubb@gmail.com<br />Users are encouraged to report technical issues, account problems, or content concerns promptly. SkillSwap Hub strives to respond within reasonable timelines and provides escalation procedures for unresolved matters. Proper communication ensures efficient resolution of refunds, disputes, or account-related issues. Users should provide accurate information in all communications. SkillSwap Hub maintains a dedicated legal and support team to protect user interests, enforce Terms, and safeguard platform integrity. Contact channels are available for queries related to wallet, subscription, gamification, AI, or content rights, ensuring a seamless and transparent experience for all users.</p>
  </div>
);

export default TermsConditions;
